Add support for concourse bbl lb

diff --git a/bbl-up/task b/bbl-up/task
--- a/bbl-up/task
+++ b/bbl-up/task
@@ -7,8 +7,18 @@ function check_fast_fails() {
   set +x
 
   if [ "${SKIP_LB_CREATION}" == "false" ]; then
-    if [ -z "${LB_DOMAIN}" ]; then
-      echo "\$LB_DOMAIN is a required parameter.  Please set the domain."
+    if [ "${BBL_LB_TYPE}" != "cf" ] && [ "${BBL_LB_TYPE}" != "concourse" ]; then
+      echo "\$BBL_LB_TYPE must be one of [cf, concourse]."
+      exit 1
+    fi
+
+    if [ -z "${LB_DOMAIN}" ] && [ "${BBL_LB_TYPE}" == "cf" ]; then
+      echo "\$LB_DOMAIN is a required parameter when \$BBL_LB_TYPE=cf.  Please set the domain."
+      exit 1
+    fi
+
+    if [ -n "${LB_DOMAIN}" ] && [ "${BBL_LB_TYPE}" == "concourse" ]; then
+      echo "\$LB_DOMAIN should not be set when \$BBL_LB_TYPE=concourse."
       exit 1
     fi
 
@@ -84,7 +94,7 @@ function main() {
       local bbl_cert_key
       write_bbl_certs
 
-      lb_flags="--lb-type=cf --lb-cert=${bbl_cert_path} ${bbl_cert_chain_flag} --lb-key=${bbl_key_path} --lb-domain=${LB_DOMAIN}"
+      lb_flags="--lb-type=${BBL_LB_TYPE} --lb-cert=${bbl_cert_path} ${bbl_cert_chain_flag} --lb-key=${bbl_key_path} --lb-domain=${LB_DOMAIN}"
     fi
 
     bbl plan \
